# Generated by Django 2.2.2 on 2019-06-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
